[package]
name = "model"
version = "0.1.0"
authors = ["josojo <josojo@hotmail.de>"]
edition = "2018"


[dependencies]
hex = { version = "0.4", default-features = false }
hex-literal = "0.3"
primitive-types = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }

