name: deploy
on:
  push:
    branches: [develop]
    tags: [v*]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URI: 024343560884.dkr.ecr.us-east-1.amazonaws.com/dex-gnosis-auction-services
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      CONTAINER_NAME: gnosis-auction-services
      ECS_SERVICE: dex-gnosis-auction-service
      ECS_CLUSTER: dex-gnosis-auction-services
      ECS_TASK_DEFINITION: gnosis-auction-services-td.json
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${GITHUB_REF#refs/*/}
      
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - run: ./docker/deploy.sh ${GITHUB_REF#refs/*/}